# Generated by Django 5.1.5 on 2025-01-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mytodo',
            new_name='MytodoModel',
        ),
    ]
